### ISSUE TITLE
A question about dynamic node features

### ISSUE THREAD

**Issue by Blue0rigin** [yule-BUAA/DyGLib#1]
Thank you for the wonderful work!

I am trying to use your temporal GNN models for my research project. But the problem is that the node features are dynamic rather than static in my case -- the feature vector of each node may change over time. I have checked your code but it seems to me that DyGLib does not support the dynamic node feature in terms of data structure and model updating (Please correct me if I am wrong). Do you have any suggestions on how to adpat your code to support the dynamic node features? Is it possible to support the dynamic_graph_temporal_signal data structure in [pytorch_geometric_temporal](https://github.com/benedekrozemberczki/pytorch_geometric_temporal)? Thanks!

**Comment by yule-BUAA** [comment]
Hello,

Thanks for your interest in our work. 

It seems that you only need some simple modifications of our codes for your requirements. 
    
In our original implementation, the nodes have static features which are stored in ```node_raw_features``` with np.ndarray structure. Since the features of nodes change over time in your project, you are able to provide the varied feature of the source and destination node at each interaction. Therefore, 1) We can first represent ```node_raw_features``` by a dictionary to store node features, where its key can be ```node_id-timestamp```, and its value should be the feature of node with ```node_id``` at time ```timestamp```; This can be modified in the ```DataLoader.py``` file. 2) When the models need to use the dynamic node features, we can retrieve them from the dictionary by constructing the key in ```node_id-timestamp``` format based on node index and interaction timestamp. These can be modified in the forward process of each model in the ```models/``` folder.

Based on the above modifications, I think your requirements can be met.

Please feel free to contact me if there are any further problems.

**Comment by Blue0rigin** [comment]
Many thanks for the thorough response. That helps a lot.
