### ISSUE TITLE
Adapting Models for Node Classification Tasks to Datasets Lacking Edge Features

### ISSUE THREAD

**Issue by qmy0701** [yule-BUAA/DyGLib#11]
Hello, I noticed that the datasets used for the node classification task in your paper all have edge features, but the dataset I am currently using does not have edge features, only node features. What is the minimal modification I can make so that the model can be applied to datasets without edge features?

**Comment by yule-BUAA** [comment]
Hi,
For your mentioned case, you can simply set the features of all edges (`edge_raw_features`) to zero vectors [here](https://github.com/yule-BUAA/DyGLib/blob/3aacc36b94b8d2d8293d70a74fdf6d39089b4163/utils/DataLoader.py#L189). Since all the edges have zero vectors as features and do not have valuable information, models would not learn from them. 
I hope this answer helps solve your issue.

**Comment by qmy0701** [comment]
Thanks for your timely reply!

**Comment by mgao97** [comment]
A simple question on how to create the original csv file for dynamic node classification, especially for the edge features? Why not for the node features? 

For the edge features, I can just set them to zero vectors. But how do I use the node features in the original csv file?

According to [the Dataset.readme,](https://github.com/yule-BUAA/DyGLib/blob/master/DG_data/DATASETS_README.md), the ml_{dataset_name}.csv, ml_{dataset_name}.npy and ml_{dataset_name_node}.npy are generated by preprocessing_data from the original csv file, is this correct?
