### ISSUE TITLE
Creating custom dynamic and temporal dataset for link prediction

### ISSUE THREAD

**Issue by ERYAGNIK003** [yule-BUAA/DyGLib#2]
I have dynamic (Nodes are created and deleted over a period of time) and temporal (node features are changing over a time) data. Then, how to create a dataset which are suitable for GNN ? Also, node features are numeric values. So, how to represent it in a .npy format ? Thanks.

**Comment by ERYAGNIK003** [comment]
Thanks for the response. I wanted to ask that you have mentioned that you have tested your code with 13 datasets (Wikipedia, Reddit, MOOC, LastFM, Enron, Social Evo., UCI, Flights, Can. Parl., US Legis., UN Trade, UN Vote, and Contact). So, none of the dataset has features that I have mentioned( node creation/deletion and node features as numerical values) ? Second, can you suggest me other potential GNNs for my job. Thanks.

**Comment by yule-BUAA** [comment]
1. Yes. Currently, all the used 13 datasets only support the additions of edges, and the node features are set to zero vectors since nodes do not have features. 
2. For your requirements, I think some dynamic GNNs for continual learning or open temporal graphs are more suitable. Just name a few works like [Streaming Graph Neural Networks via Continual Learning (CIKM 2020)](https://arxiv.org/abs/2009.10951), [Towards Open Temporal Graph Neural Networks (ICLR 2023)](https://openreview.net/forum?id=N9Pk5iSCzAn), and [Continual Learning on Dynamic Graphs via Parameter Isolation (SIGIR 2023)](https://arxiv.org/abs/2305.13825).
