### ISSUE TITLE
[Help] Why Node ID starts from 1 instead of 0?

### ISSUE THREAD

**Issue by bwdeng20** [yule-BUAA/DyGLib#5]
Thanks for your efforts!
I am confused by the `reindex`  operation in `preprocess_data.py` since the JOIDE datasets implemented in  [PyG](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/jodie.html) start node index from 0 instead of 1 here.

Could you tell me why DyGLib (and [DGB](https://github.com/fpour/DGB)) take such reindex operations?

**Comment by yule-BUAA** [comment]
Hello,

Thanks for your interest in our work!

We make the node ids and edge ids start from 1 because we use the node/edge with id 0 as the mask node/edge, which is easy to implement. Their features are also set to zero vectors. The mask node/edge is then used for padding by the dynamic graph learning methods. 

For example, we pad the neighbors in `NeighborSampler` [here](https://github.com/yule-BUAA/DyGLib/blob/2b5c9f6cd36cf0ae354b7e3788c56749ed8f9a3b/utils/utils.py#L161) and pad the edges [here](https://github.com/yule-BUAA/DyGLib/blob/2b5c9f6cd36cf0ae354b7e3788c56749ed8f9a3b/utils/utils.py#L164). Then, the dynamic graph learning methods perform masked computations. For instance, the causal attention [here](https://github.com/yule-BUAA/DyGLib/blob/2b5c9f6cd36cf0ae354b7e3788c56749ed8f9a3b/models/modules.py#L177).

I hope this answer has well addressed your issue. And feel free to ask if there are any further questions.

Best,

Le Yu

**Comment by bwdeng20** [comment]
Thanks for your swift response :) I am actually still confused. I think need some time to compare the CTDG implementations from PyG, DyGLib, and those official repos so that I can have a comprehensive understanding.

**Comment by yule-BUAA** [comment]
I hope you are doing well. And welcome to contact me if there are any issues with our DyGLib.
